.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bubcoin_qt test_bubcoin_qt
clean: FORCE
	$(MAKE) -C .. bubcoin_qt_clean test_bubcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bubcoin_qt_check
bubcoin-qt bubcoin-qt.exe: FORCE
	 $(MAKE) -C .. bubcoin_qt
